version: '3.2'

services:
  mongodb:
    image: mongo
    restart: always
  redis:
    image: redis
    restart: always
  fiora:
    build: .
    restart: always
    ports:
      - "9200:9200"
    environment:
      - Database=mongodb+srv://Bot:rattlesnake20@cluster0.ehnrp.mongodb.net/?retryWrites=true&w=majority
      - RedisHost=redis-19086.c1.asia-northeast1-1.gce.cloud.redislabs.com
